<?php

namespace AppBundle\Repository;

/**
 * AmigoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmigoRepository extends \Doctrine\ORM\EntityRepository
{
}
