<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChatUsuarioUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatUsuarioUsuarioRepository extends EntityRepository
{
  public function findComentariosNoVistosPorUsuario($usuario , $yo)
  {


      $query = $this->getEntityManager()
          ->createQuery(
              'SELECT c , u ,d
              FROM AppBundle:ChatUsuarioUsuario c
                JOIN
                c.usuario u
                JOIN
                c.direccion d
              WHERE (c.usuario  = :usuario AND c.direccion = :direccion ) OR (c.usuario = :direccion AND c.direccion = :usuario)
              ORDER BY c.id
              '
          )
          ->setParameter('usuario', $yo)
          ->setParameter('direccion', $usuario);
          $usuarios = $query->getArrayResult();

          return $usuarios;

  }
  public function findMensajesNUevos($yo)
  {
      $query = $this->getEntityManager()
          ->createQuery(
              'SELECT c , u ,d
              FROM AppBundle:ChatUsuarioUsuario c
                JOIN
                c.usuario u
                JOIN
                c.direccion d
              WHERE c.direccion  = :direccion AND c.visto = :visto
              ORDER BY c.id
              '
          )
          ->setParameter('direccion', $yo)
          ->setParameter('visto', 0);
          $usuarios = $query->getArrayResult();
          return $usuarios;
  }
  public function chatsRecientes($yo)
  {
      $query = $this->getEntityManager()
          ->createQuery(
              'SELECT c , u ,d
              FROM AppBundle:ChatUsuarioUsuario c
                JOIN
                c.direccion d
                JOIN
                c.usuario u
              WHERE c.direccion  = :direccion
              GROUP BY u.id
              '
          )
          ->setParameter('direccion', $yo);
          $chats = $query->getArrayResult();
          return $chats;
  }


}
