<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ComentarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComentarioRepository extends EntityRepository
{
  public function findComentariosNoVistosPorUsuario($usuario)
  {
      $query = $this->getEntityManager()
          ->createQuery(
              'SELECT c  FROM AppBundle:Comentario c
              JOIN c.publicacion p
              WHERE p.usuario  = :usuario
              AND c.visto = 0
              ORDER BY c.createdAt DESC
              '
          )
          ->setParameter('usuario', $usuario->getId());
          $comentarios = $query->getResult();

          return $comentarios;

  }
}
