<?php

namespace AppBundle\Repository;

/**
 * ConversacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConversacionRepository extends \Doctrine\ORM\EntityRepository
{

    

    public function findConversacion($yo)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT c   
                FROM AppBundle:Conversacion c
                WHERE c.usuarioUno  = :usuario'
            )
            ->setParameter('usuario', $yo);
            $chats = $query->getResult();
            return $chats;
    }
}
