<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Empresa_favoritaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Empresa_favoritaRepository extends EntityRepository
{
}
