<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresaRepository extends EntityRepository
{

    public function findEmpresaPorNombre($nombre,$municipioId)
  {
      if ($nombre!="") {
            $query = $this->getEntityManager()
            ->createQuery(
                'SELECT e  FROM AppBundle:Empresa e
                WHERE e.nombre  LIKE :nombre'
            )
            ->setParameter('nombre', '%'.$nombre.'%');
        }
        if ($municipioId!="") {
            $query = $this->getEntityManager()
            ->createQuery(
                'SELECT e  FROM AppBundle:Empresa e
                WHERE e.municipio = :municipio'
            )
            ->setParameter('municipio', $municipioId);
        }
        if (($nombre!="") && ($municipioId !="")) {
            $query = $this->getEntityManager()
            ->createQuery(
              'SELECT e  FROM AppBundle:Empresa e
              WHERE e.nombre  LIKE :nombre
              AND e.municipio = :municipio'
          )
          ->setParameter('nombre', '%'.$nombre.'%')
          ->setParameter('municipio', $municipioId);
        }
        if (($municipioId =='') && ($nombre=='')) {
            
            $query = $this->getEntityManager()
            ->createQuery(
                'SELECT e  FROM AppBundle:Empresa e'
            );
        }
        $productos = $query->getResult();
        return $productos;
  }
}
