<?php

namespace AppBundle\Repository;

/**
 * EmpresaSubastaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresaSubastaRepository extends \Doctrine\ORM\EntityRepository
{
}
