<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresaRepository extends EntityRepository
{
<<<<<<< HEAD

    public function findEmpresaPorNombre($nombre,$municipioId)
  {
      if ($nombre!="") {
            $query = $this->getEntityManager()
            ->createQuery(
                'SELECT e  FROM AppBundle:Empresa e
                WHERE e.nombre  LIKE :nombre'
            )
            ->setParameter('nombre', '%'.$nombre.'%');
        }
        if ($municipioId!="") {
            $query = $this->getEntityManager()
            ->createQuery(
                'SELECT e  FROM AppBundle:Empresa e
                WHERE e.municipio = :municipio'
            )
            ->setParameter('municipio', $municipioId);
        }
        if (($nombre!="") && ($municipioId !="")) {
            $query = $this->getEntityManager()
            ->createQuery(
=======
    public function finEmpresaNombre($nombre,$municipioId)
  {
      
      $query = $this->getEntityManager()
          ->createQuery(
>>>>>>> 356f9372a20170dda02e0945068b818f7be736de
              'SELECT e  FROM AppBundle:Empresa e
              WHERE e.nombre  LIKE :nombre
              AND e.municipio = :municipio'
          )
          ->setParameter('nombre', '%'.$nombre.'%')
<<<<<<< HEAD
          ->setParameter('municipio', $municipioId);
        }
        if (($municipioId =='') && ($nombre=='')) {
            
            $query = $this->getEntityManager()
            ->createQuery(
                'SELECT e  FROM AppBundle:Empresa e'
            );
        }
        $productos = $query->getResult();
        return $productos;
=======
          ->setParameter('municipio', $municipioId)
          ;

          $productos = $query->getResult();
          return $productos;
>>>>>>> 356f9372a20170dda02e0945068b818f7be736de
  }
}
