<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoRepository extends EntityRepository
{
  public function findProductosPorNombre($nombre)
  {
      $query = $this->getEntityManager()
          ->createQuery(
              'SELECT p , e  FROM AppBundle:Producto p
              JOIN p.empresa e
              WHERE p.tags  LIKE :nombre
              AND p.activo = 1
              AND e.activo = 1
              ORDER BY  e.posicionamiento ASC
              '
          )
          ->setParameter('nombre', '%'.$nombre.'%');
          $productos = $query->getResult();

          return $productos;

  }

  public function findProductosPorNombreYEmpresa($nombre,$empresa)
  {
      $idEmpresa = $empresa->getId();
      $query = $this->getEntityManager()
          ->createQuery(
              'SELECT p  FROM AppBundle:Producto p
              JOIN p.empresa e
              WHERE p.tags  LIKE :nombre
              AND e.id = :empresa'
          )
          ->setParameter('nombre', '%'.$nombre.'%')
          ->setParameter('empresa', $idEmpresa);

          $productos = $query->getResult();
          return $productos;
  }

  public function findProductosPorNombreCategoriaMunicipio($nombre,$municipioId,$categoriaId)
  {
      
      $query = $this->getEntityManager()
          ->createQuery(
              'SELECT p  FROM AppBundle:Producto p
              JOIN p.empresa e
              WHERE p.tags  LIKE :nombre
              AND e.municipio = :municipio
              AND p.subCategoria =:categoria'
          )
          ->setParameter('nombre', '%'.$nombre.'%')
          ->setParameter('municipio', $municipioId)
          ->setParameter('categoria', $categoriaId);
          ;

          $productos = $query->getResult();
          return $productos;
  }
}
