<?php

namespace AppBundle\Repository;

/**
 * SubastaProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubastaProductoRepository extends \Doctrine\ORM\EntityRepository
{
    
}
