<?php

namespace AppBundle\Repository;

/**
 * SubastaProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubastaProductoRepository extends \Doctrine\ORM\EntityRepository
{

    public function findSubastaPorEmpresa($empresaId)
    {
        
    $query = $this->getEntityManager()
        ->createQuery(
            'SELECT se  FROM AppBundle:SubastaProducto se
            JOIN se.subasta s
            WHERE se.empresa  = :empresaId
            AND s.estado = :solicitado'
        )
        ->setParameter('empresaId', $empresaId)
        ->setParameter('solicitado', "solicitado");

        $subastas = $query->getResult();
        return $subastas;
    }
    
}
