<?php

namespace AppBundle\Repository;

/**
 * SubastaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubastaRepository extends \Doctrine\ORM\EntityRepository
{

    public function findSubastaPorEmpresa($empresaId)
    {
        
    $query = $this->getEntityManager()
        ->createQuery(
            'SELECT s  FROM AppBundle:Subasta s
            JOIN s.producto p
            WHERE p.empresa  = :empresaId'
        )
        ->setParameter('empresaId', $empresaId);
        ;

        $subastas = $query->getResult();
        return $subastas;
    }

}
