<?php

namespace AppBundle\Repository;

/**
 * SubastaComentarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubastaComentarioRepository extends \Doctrine\ORM\EntityRepository
{
}
