<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Tipo360Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Tipo360Repository extends EntityRepository
{
}
