<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository
{
  public function findUsuariosPorAnio()
  {
      $fecha = new \DateTime("now");
      $query = $this->getEntityManager()
          ->createQuery(
              'SELECT u  FROM AppBundle:Usuario u
              WHERE u.createdAt  >= :anio
              '
          )
          ->setParameter('anio', $fecha->format("Y")+"-01-01");
          $comentarios = $query->getResult();
          return $comentarios;
  }

  

}
