app_subasta:
    resource: "@AppBundle/Controller/SubastaController.php"
    type:     annotation

app_amigo:
    resource: "@AppBundle/Controller/AmigoController.php"
    type:     annotation

app_comentario:
    resource: "@AppBundle/Controller/ComentarioController.php"
    type:     annotation

app_publicacion:
    resource: "@AppBundle/Controller/PublicacionController.php"
    type:     annotation

app_producto_promocion:
    resource: "@AppBundle/Controller/productoPromocionController.php"
    type:     annotation

app_baner_publicidad:
    resource: "@AppBundle/Controller/BanerPublicidadController.php"
    type:     annotation

app_producto_imagen:
    resource: "@AppBundle/Controller/ProductoImagenController.php"
    type:     annotation

app_producto:
    resource: "@AppBundle/Controller/ProductoController.php"
    type:     annotation

app_imagen_empresa:
    resource: "@AppBundle/Controller/ImagenEmpresaController.php"
    type:     annotation

app_empresa:
    resource: "@AppBundle/Controller/EmpresaController.php"
    type:     annotation

# mapps_usuario_api:
#     resource: "@MappsUsuarioBundle/Controller/"
#     type:     rest
#     prefix:   /api

mapps_usuario_web:
    resource: "@MappsUsuarioBundle/Controller/"
    type:     annotation

mapps_usuario_api:
    resource: "@MappsUsuarioBundle/ControllerApi/"
    type:     rest
    prefix:   /api

app_controller_api:
    resource: "@AppBundle/ControllerApi/"
    type:     annotation
    prefix:   /api

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


# app/config/routing.yml
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml" 